name: Niam
options:
  bundleIdPrefix: com.brinnyni
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"
    GENERATE_INFOPLIST_FILE: true
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: "0.1.0"

targets:
  Niam:
    type: application
    platform: iOS
    sources:
      - Niam
    settings:
      base:
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown"
        INFOPLIST_KEY_CFBundleDisplayName: "Niam"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_EMIT_LOC_STRINGS: true
        ENABLE_PREVIEWS: true

  NiamTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - NiamTests
    dependencies:
      - target: Niam
    settings:
      base:
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Niam.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Niam"
